---
title: "Data_preprocessing"
author: "Zidao Wang"
date: "2025-04-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(dplyr)
library(Seurat)
library(patchwork)
library(sctransform)
library(ggplot2)
library(harmony)
library(hdf5r)
library(clusterProfiler)
library(AnnotationDbi)
library(org.Mm.eg.db)
library(scDblFinder)
library(fgsea)
library(tidyverse)
library(DT)
library(enrichplot)
library(monocle3)
library(SeuratWrappers)
library(pheatmap)
library(AUCell)
library(CellChat)
library(reticulate)
library(circlize)
library(NMF)
library(ggalluvial)
library(readxl)
library(openxlsx)
library(ComplexHeatmap)
library(eulerr)
library(VennDiagram)
library(loupeR)
library(EnhancedVolcano)
library(CytoTRACE2)
library(RColorBrewer)
library(viridis)
library(ggrastr)
library(reshape2)
library(ggridges)
library(gt)
library(ggVennDiagram)
library(concaveman)
library(dbscan)

# Load the P-Ai14 dataset
Ai14_94.data <- Read10X_h5("./94_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_143.data <- Read10X_h5("./143_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_81.data <- Read10X_h5("./81_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_38.data <- Read10X_h5("./38_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_55.data <- Read10X_h5("./55_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_153.data <- Read10X_h5("./153_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_51.data <- Read10X_h5("./51_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_162.data <- Read10X_h5("./162_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_97.data <- Read10X_h5("./97_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_105.data <- Read10X_h5("./105_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_360.data <- Read10X_h5("./360_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")
Ai14_372.data <- Read10X_h5("./372_cellbender_filtered_feature_bc_matrix_FPR_0.05_filtered_Seurat.h5")

# Initialize the Seurat object with the raw (non-normalized data).
Ai14_94 <- CreateSeuratObject(counts = Ai14_94.data, project = "Ai14_94_E18.5", min.cells = 3, min.features = 200)
Ai14_143 <- CreateSeuratObject(counts = Ai14_143.data, project = "Ai14_143_E18.5", min.cells = 3, min.features = 200)
Ai14_81 <- CreateSeuratObject(counts = Ai14_81.data, project = "Ai14_81_PPD1", min.cells = 3, min.features = 200)
Ai14_38 <- CreateSeuratObject(counts = Ai14_38.data, project = "Ai14_38_PPD1", min.cells = 3, min.features = 200)
Ai14_55 <- CreateSeuratObject(counts = Ai14_55.data, project = "Ai14_55_PPD2", min.cells = 3, min.features = 200)
Ai14_153 <- CreateSeuratObject(counts = Ai14_153.data, project = "Ai14_153_PPD2", min.cells = 3, min.features = 200)
Ai14_51 <- CreateSeuratObject(counts = Ai14_51.data, project = "Ai14_51_PPD3", min.cells = 3, min.features = 200)
Ai14_162 <- CreateSeuratObject(counts = Ai14_162.data, project = "Ai14_162_PPD3", min.cells = 3, min.features = 200)
Ai14_97 <- CreateSeuratObject(counts = Ai14_97.data, project = "Ai14_97_PPD4", min.cells = 3, min.features = 200)
Ai14_105 <- CreateSeuratObject(counts = Ai14_105.data, project = "Ai14_105_PPD4", min.cells = 3, min.features = 200)
Ai14_360 <- CreateSeuratObject(counts = Ai14_360.data, project = "Ai14_360_PPD28", min.cells = 3, min.features = 200)
Ai14_372 <- CreateSeuratObject(counts = Ai14_372.data, project = "Ai14_372_PPD28", min.cells = 3, min.features = 200)

# Doublet filtering Doublet
Ai14_94.sce <- as.SingleCellExperiment(Ai14_94) # Convert to single cell experiment format
Ai14_94.sce <- scDblFinder(Ai14_94.sce) # run scDblFinder with default settings.
Ai14_94$scDblFinder.score <- Ai14_94.sce$scDblFinder.score # add the score to the seurat object metadata
Ai14_94$scDblFinder.class <- Ai14_94.sce$scDblFinder.class # add the classification of doublet or not

Ai14_143.sce <- as.SingleCellExperiment(Ai14_143)
Ai14_143.sce <- scDblFinder(Ai14_143.sce)
Ai14_143$scDblFinder.score <- Ai14_143.sce$scDblFinder.score
Ai14_143$scDblFinder.class <- Ai14_143.sce$scDblFinder.class

Ai14_81.sce <- as.SingleCellExperiment(Ai14_81)
Ai14_81.sce <- scDblFinder(Ai14_81.sce)
Ai14_81$scDblFinder.score <- Ai14_81.sce$scDblFinder.score
Ai14_81$scDblFinder.class <- Ai14_81.sce$scDblFinder.class

Ai14_38.sce <- as.SingleCellExperiment(Ai14_38)
Ai14_38.sce <- scDblFinder(Ai14_38.sce)
Ai14_38$scDblFinder.score <- Ai14_38.sce$scDblFinder.score
Ai14_38$scDblFinder.class <- Ai14_38.sce$scDblFinder.class

Ai14_55.sce <- as.SingleCellExperiment(Ai14_55)
Ai14_55.sce <- scDblFinder(Ai14_55.sce)
Ai14_55$scDblFinder.score <- Ai14_55.sce$scDblFinder.score
Ai14_55$scDblFinder.class <- Ai14_55.sce$scDblFinder.class

Ai14_153.sce <- as.SingleCellExperiment(Ai14_153)
Ai14_153.sce <- scDblFinder(Ai14_153.sce)
Ai14_153$scDblFinder.score <- Ai14_153.sce$scDblFinder.score
Ai14_153$scDblFinder.class <- Ai14_153.sce$scDblFinder.class

Ai14_51.sce <- as.SingleCellExperiment(Ai14_51)
Ai14_51.sce <- scDblFinder(Ai14_51.sce)
Ai14_51$scDblFinder.score <- Ai14_51.sce$scDblFinder.score
Ai14_51$scDblFinder.class <- Ai14_51.sce$scDblFinder.class

Ai14_162.sce <- as.SingleCellExperiment(Ai14_162)
Ai14_162.sce <- scDblFinder(Ai14_162.sce)
Ai14_162$scDblFinder.score <- Ai14_162.sce$scDblFinder.score
Ai14_162$scDblFinder.class <- Ai14_162.sce$scDblFinder.class

Ai14_97.sce <- as.SingleCellExperiment(Ai14_97)
Ai14_97.sce <- scDblFinder(Ai14_97.sce)
Ai14_97$scDblFinder.score <- Ai14_97.sce$scDblFinder.score
Ai14_97$scDblFinder.class <- Ai14_97.sce$scDblFinder.class

Ai14_105.sce <- as.SingleCellExperiment(Ai14_105)
Ai14_105.sce <- scDblFinder(Ai14_105.sce)
Ai14_105$scDblFinder.score <- Ai14_105.sce$scDblFinder.score
Ai14_105$scDblFinder.class <- Ai14_105.sce$scDblFinder.class

Ai14_360.sce <- as.SingleCellExperiment(Ai14_360)
Ai14_360.sce <- scDblFinder(Ai14_360.sce)
Ai14_360$scDblFinder.score <- Ai14_360.sce$scDblFinder.score
Ai14_360$scDblFinder.class <- Ai14_360.sce$scDblFinder.class

Ai14_372.sce <- as.SingleCellExperiment(Ai14_372)
Ai14_372.sce <- scDblFinder(Ai14_372.sce)
Ai14_372$scDblFinder.score <- Ai14_372.sce$scDblFinder.score
Ai14_372$scDblFinder.class <- Ai14_372.sce$scDblFinder.class

# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
Ai14_94[["percent.mt"]] <- PercentageFeatureSet(Ai14_94, pattern = "^mt-")
Ai14_143[["percent.mt"]] <- PercentageFeatureSet(Ai14_143, pattern = "^mt-")
Ai14_81[["percent.mt"]] <- PercentageFeatureSet(Ai14_81, pattern = "^mt-")
Ai14_38[["percent.mt"]] <- PercentageFeatureSet(Ai14_38, pattern = "^mt-")
Ai14_55[["percent.mt"]] <- PercentageFeatureSet(Ai14_55, pattern = "^mt-")
Ai14_153[["percent.mt"]] <- PercentageFeatureSet(Ai14_153, pattern = "^mt-")
Ai14_51[["percent.mt"]] <- PercentageFeatureSet(Ai14_51, pattern = "^mt-")
Ai14_162[["percent.mt"]] <- PercentageFeatureSet(Ai14_162, pattern = "^mt-")
Ai14_97[["percent.mt"]] <- PercentageFeatureSet(Ai14_97, pattern = "^mt-")
Ai14_105[["percent.mt"]] <- PercentageFeatureSet(Ai14_105, pattern = "^mt-")
Ai14_360[["percent.mt"]] <- PercentageFeatureSet(Ai14_360, pattern = "^mt-")
Ai14_372[["percent.mt"]] <- PercentageFeatureSet(Ai14_372, pattern = "^mt-")

Ai14_94[["percent.rps"]] <- PercentageFeatureSet(Ai14_94, pattern= "(?i)rp[ls]")
Ai14_143[["percent.rps"]] <- PercentageFeatureSet(Ai14_143, pattern= "(?i)rp[ls]")
Ai14_81[["percent.rps"]] <- PercentageFeatureSet(Ai14_81, pattern= "(?i)rp[ls]")
Ai14_38[["percent.rps"]] <- PercentageFeatureSet(Ai14_38, pattern= "(?i)rp[ls]")
Ai14_55[["percent.rps"]] <- PercentageFeatureSet(Ai14_55, pattern= "(?i)rp[ls]")
Ai14_153[["percent.rps"]] <- PercentageFeatureSet(Ai14_153, pattern= "(?i)rp[ls]")
Ai14_51[["percent.rps"]] <- PercentageFeatureSet(Ai14_51, pattern= "(?i)rp[ls]")
Ai14_162[["percent.rps"]] <- PercentageFeatureSet(Ai14_162, pattern= "(?i)rp[ls]")
Ai14_97[["percent.rps"]] <- PercentageFeatureSet(Ai14_97, pattern= "(?i)rp[ls]")
Ai14_105[["percent.rps"]] <- PercentageFeatureSet(Ai14_105, pattern= "(?i)rp[ls]")
Ai14_360[["percent.rps"]] <- PercentageFeatureSet(Ai14_360, pattern= "(?i)rp[ls]")
Ai14_372[["percent.rps"]] <- PercentageFeatureSet(Ai14_372, pattern= "(?i)rp[ls]")

# Visualize QC metrics as a violin plot
#VlnPlot(Ai14_94, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rps"), ncol = 4)
#VlnPlot(Ai14_81, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rps"), ncol = 4)
#VlnPlot(Ai14_55, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rps"), ncol = 4)
#VlnPlot(Ai14_51, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rps"), ncol = 4)
#VlnPlot(Ai14_97, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rps"), ncol = 4)

#rRNA and mtRNA filter
Ai14_94 <- subset(Ai14_94, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_143 <- subset(Ai14_143, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_81 <- subset(Ai14_81, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_38 <- subset(Ai14_38, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_55 <- subset(Ai14_55, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_153 <- subset(Ai14_153, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_51 <- subset(Ai14_51, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_162 <- subset(Ai14_162, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_97 <- subset(Ai14_97, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_105 <- subset(Ai14_105, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_360 <- subset(Ai14_360, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")
Ai14_372 <- subset(Ai14_372, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 5 & percent.rps < 7 & scDblFinder.score < 0.75 & scDblFinder.class == "singlet")

#Adding a column to the metadata

Ai14_94@meta.data$groups <- "E18.5"
Ai14_143@meta.data$groups <- "E18.5"
Ai14_81@meta.data$groups <- "PPD1"
Ai14_38@meta.data$groups <- "PPD1"
Ai14_55@meta.data$groups <- "PPD2"
Ai14_153@meta.data$groups <- "PPD2"
Ai14_51@meta.data$groups <- "PPD3"
Ai14_162@meta.data$groups <- "PPD3"
Ai14_97@meta.data$groups <- "PPD4"
Ai14_105@meta.data$groups <- "PPD4"
Ai14_360@meta.data$groups <- "PPD28"
Ai14_372@meta.data$groups <- "PPD28"

#SCTransform

Ai14_94 <- SCTransform(Ai14_94, assay="RNA", verbose=TRUE)
Ai14_143 <- SCTransform(Ai14_143, assay="RNA", verbose=TRUE)
Ai14_81 <- SCTransform(Ai14_81, assay="RNA", verbose=TRUE)
Ai14_38 <- SCTransform(Ai14_38, assay="RNA", verbose=TRUE)
Ai14_55 <- SCTransform(Ai14_55, assay="RNA", verbose=TRUE)
Ai14_153 <- SCTransform(Ai14_153, assay="RNA", verbose=TRUE)
Ai14_51 <- SCTransform(Ai14_51, assay="RNA", verbose=TRUE)
Ai14_162 <- SCTransform(Ai14_162, assay="RNA", verbose=TRUE)
Ai14_97 <- SCTransform(Ai14_97, assay="RNA", verbose=TRUE)
Ai14_105 <- SCTransform(Ai14_105, assay="RNA", verbose=TRUE)
Ai14_360 <- SCTransform(Ai14_360, assay="RNA", verbose=TRUE)
Ai14_372 <- SCTransform(Ai14_372, assay="RNA", verbose=TRUE)

#Integration
Ai14_94 <- RunPCA(Ai14_94, assay="SCT", verbose=FALSE)
Ai14_143 <- RunPCA(Ai14_143, assay="SCT", verbose=FALSE)
Ai14_81 <- RunPCA(Ai14_81, assay="SCT", verbose=FALSE)
Ai14_38 <- RunPCA(Ai14_38, assay="SCT", verbose=FALSE)
Ai14_55 <- RunPCA(Ai14_55, assay="SCT", verbose=FALSE)
Ai14_153 <- RunPCA(Ai14_153, assay="SCT", verbose=FALSE)
Ai14_51 <- RunPCA(Ai14_51, assay="SCT", verbose=FALSE)
Ai14_162 <- RunPCA(Ai14_162, assay="SCT", verbose=FALSE)
Ai14_97 <- RunPCA(Ai14_97, assay="SCT", verbose=FALSE)
Ai14_105 <- RunPCA(Ai14_105, assay="SCT", verbose=FALSE)
Ai14_360 <- RunPCA(Ai14_360, assay="SCT", verbose=FALSE)
Ai14_372 <- RunPCA(Ai14_372, assay="SCT", verbose=FALSE)

#Merge all samples
all_merged <- merge(Ai14_94, c(Ai14_143, Ai14_81, Ai14_38, Ai14_55, Ai14_153, Ai14_51, Ai14_162, Ai14_97, Ai14_105, Ai14_360, Ai14_372), add.cell.ids = c("E18.5", "E18.5", "PPD1", "PPD1", "PPD2", "PPD2", "PPD3", "PPD3", "PPD4", "PPD4", "PPD28", "PPD28"))

#Assign default assay for downstream analysis
DefaultAssay(all_merged) <- "SCT"

VariableFeatures(all_merged) <- c(VariableFeatures(Ai14_94), VariableFeatures(Ai14_143), VariableFeatures(Ai14_81), VariableFeatures(Ai14_38), VariableFeatures(Ai14_55), VariableFeatures(Ai14_153), VariableFeatures(Ai14_51), VariableFeatures(Ai14_162), VariableFeatures(Ai14_97), VariableFeatures(Ai14_105), VariableFeatures(Ai14_360), VariableFeatures(Ai14_372))

#SCTransform to the merged sample
all_merged <- SCTransform(object = all_merged)

all_merged_harmony <- RunPCA(all_merged, assay="SCT", verbose=TRUE)
all_merged_harmony <- IntegrateLayers(object = all_merged_harmony, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = "harmony", layers = "data", assay = "SCT", verbose = TRUE)
all_merged_harmony <- FindNeighbors(object = all_merged_harmony, reduction="harmony", dims=1:30)
all_merged_harmony_cluster <- FindClusters(all_merged_harmony, resolution=0.5, verbose=FALSE)
all_merged_harmony_cluster <- RunUMAP(all_merged_harmony_cluster, reduction = "harmony", assay = "SCT", dims = 1:30)
all_merged_harmony_cluster_v2_PrepSCT_12sample <- PrepSCTFindMarkers(all_merged_harmony_cluster, assay = "SCT", verbose = TRUE)

saveRDS(all_merged_harmony_cluster_v2_PrepSCT_12sample, file = "/cluster/pixstor/pattersonama-lab/zidao/RNA-seq-analysis/Results/rRNA_removed/Cellbender_pipeline_v2_ignore_features_fpr005/all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5.rds")

#Read RDS file
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5 <- readRDS("all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5.rds")

#Cluster annotation for the merged sample
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5.markers <- FindAllMarkers(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, logfc.threshold = 1, 
                                                                             min.pct = 0.05, verbose = TRUE, only.pos = TRUE)

#Rename clusters
new.cluster.ids <- c("Epithelial cells-1", "Endothelial cells-1", "Mesenchymal cells-1", "Transitional cells", 
                     "Mesenchymal cells-2", "Mesenchymal cells-3", "Immune cells-1", "Endothelial cells-2", "Immune cells-2", 
                     "Myometrial cells", "Epithelial cells-2", "Epithelial cells-3", "Epithelial cells-4", "Immune cells-3", 
                     "Perivascular cells", "Epithelial cells-5", "Immune cells-4", "Epithelial cells-6", 
                     "Epithelial cells-7", "Epithelial cells-8", "Plasma cells", "Trophoblast cells", "Immune cells-5", 
                     "Endothelial cells-3", "Epithelial cells-9" 
                     )
names(new.cluster.ids) <- levels(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5)
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5 <- RenameIdents(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, new.cluster.ids)

#Add cluster names to the metadata
cluster_letters <- new.cluster.ids[Idents(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5)]
names(cluster_letters) <- colnames(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5)
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5 <- AddMetaData(
  object = all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5,
  metadata = cluster_letters,
  col.name = 'cluster_names')

#Subset epithelial cells
Idents(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) <- "cluster_names"
Epi <- subset(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, idents = c("Epithelial cells-1", "Epithelial cells-2", "Epithelial cells-3", 
                                                                             "Epithelial cells-4", "Epithelial cells-5", "Epithelial cells-6", 
                                                                             "Epithelial cells-7", "Epithelial cells-8", "Epithelial cells-9"))
Epi <- RunPCA(Epi, assay="SCT", verbose=TRUE)
Epi <- FindNeighbors(Epi, reduction="harmony", dims=1:30)
Epi <- FindClusters(Epi, resolution=0.5, verbose=FALSE)
Epi <- RunUMAP(Epi, reduction = "harmony", assay = "SCT", dims = 1:30)

#Subset MD and Non_MD epithelial cells
MD <- subset(Epi, idents = c(0, 11)) 
Non_MD <- subset(Epi, idents = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13))

#Subset transitional  cells
Trans <- subset(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, idents = "Transitional cells")
Trans <- RunPCA(Trans, assay="SCT", verbose=TRUE)
Trans <- FindNeighbors(Trans, reduction="harmony", dims=1:30)
Trans <- FindClusters(Trans, resolution=0.8, verbose=FALSE)
Trans <- RunUMAP(Trans, reduction = "harmony", assay = "SCT", dims = 1:30)

#Subset MD trans and Non_MD trans cells
Trans_tdTomatoH <- subset(Trans, idents = c(2, 3))
Trans_tdTomatoL <- subset(Trans, idents = c(0, 1, 4, 5, 6, 7, 8))

#Add MD, Non_MD, Trans_tdTomatoH, Trans_tdTomatoL to the metadata
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5@meta.data$Trans_MD_cell <- all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5@meta.data$cluster_names
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5@meta.data <- all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5@meta.data %>% 
  mutate (
    Trans_MD_cell = case_when (
      colnames(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) %in% colnames(MD) ~ "MD", 
      colnames(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) %in% colnames(Non_MD) ~ "Non_MD", 
      colnames(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) %in% colnames(Trans_tdTomatoH) ~ "Trans_tdTomatoH",
      colnames(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) %in% colnames(Trans_tdTomatoL) ~ "Trans_tdTomatoL",
      TRUE ~ Trans_MD_cell))
