---
title: "Fig. 2D"
author: "Zidao Wang"
date: "2025-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Create Feature plot of genes comparing MD and Non_MD
Idents(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) <- "Trans_MD_cell"
sub <- subset(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, idents = c("Non_MD", "MD"))
sub <- PrepSCTFindMarkers(sub, assay = "SCT", verbose = TRUE)
sub@active.ident <- factor(sub@active.ident, levels = c("Non_MD", "MD"))

# Extract UMAP coordinates
umap_coords <- as.data.frame(Embeddings(sub, "umap"))
umap_coords$cell <- rownames(umap_coords)
umap_coords$Trans_MD_cell <- sub$Trans_MD_cell

# Filter for MD cells
md_coords <- umap_coords[umap_coords$Trans_MD_cell == "MD", ]
# Set parameters for DBSCAN
eps <- 0.08  # Maximum distance between two points to be considered neighbors
minPts <- 1  # Minimum number of points to form a dense region (cluster)

# Apply DBSCAN
clustering <- dbscan(md_coords[, c("umap_1", "umap_2")], eps = eps, minPts = minPts)

# Add cluster labels to md_coords
md_coords$cluster <- clustering$cluster
# Identify the major cluster
major_cluster <- which.max(table(md_coords$cluster))
# Filter for major cluster cells
major_cluster_coords <- md_coords[md_coords$cluster == major_cluster, ]
# Compute the convex hull
hull_indices <- chull(major_cluster_coords$umap_1, major_cluster_coords$umap_2)
hull_indices <- c(hull_indices, hull_indices[1])  # Close the polygon
hull_coords <- major_cluster_coords[hull_indices, ]
# Create the FeaturePlot for genes of interest
genes_of_interest <- c(“Trpv6”, “Ceacam1”, “Muc1”, “Hsd11b1”, “Hsd17b2”, “Akr1c18”, “Pgr”, “Esr1”)
p <- FeaturePlot(sub, features = genes_of_interest, order = TRUE)

# Overlay the convex hull
plot <- p + 
  geom_polygon(data = hull_coords, aes(x = umap_1, y = umap_2),
               fill = NA, color = "black", size = 0.5) +
  scale_color_gradientn(colors = c("#e6e8e8", "#fcfc00", "#bb0c00")) +
  theme(
    plot.title = element_blank(), # Remove plot title
    axis.line = element_blank(),  # Remove axis lines
    axis.text = element_blank(),  # Remove axis text
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),     # Remove x-axis title
    axis.title.y = element_blank(),     # Remove y-axis title# Remove axis ticks
    #legend.position = c(0.9, 0.9)
  )

#Create dot plot for genes of interest
DotPlot(sub, features = c("Trpv6", "Ceacam1", "Muc1", "Hsd17b2", "Hsd11b1", "Akr1c18", "Pgr", "Esr1"), 
        scale = F, col.min = 0, col.max = 2) + RotatedAxis()
