---
title: "Fig. 2F"
author: "Zidao Wang"
date: "2026-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Cnetplot
##Copy row names into a new column named 'gene_id'
MD.markers1$gene_id <- rownames(MD.markers1)
##Optional: Move the new column to the first position
MD.markers1 <- MD.markers1[, c("gene_id", setdiff(names(MD.markers1), "gene_id"))]
###Create a data frame for Foldchange argument in cnetplot
fold_changes <- setNames(MD.markers1$avg_log2FC, MD.markers1$gene_id)
fold_changes <- sort(fold_changes, decreasing = T)
###Define a vector of specific GO terms
selected_terms <- c("actin filament organization", "wound healing", "positive regulation of cell-cell adhesion", 
                    "positive regulation of cell projection organization", "small GTPase mediated signal transduction")
####Plot cnetplot
cnetplot(
  GO_results,
  showCategory = selected_terms,
  color.params = list(foldChange = fold_changes, edge = T),
  layout = "kk",
  circular = F,
  ggplot2.params = list(
    max.overlaps = 500  # Increase the max number of overlaps allowed
  )
) + scale_color_gradientn(
  name = "Fold Change",
  colors = c("blue", "white", "red"),  # Define multiple colors
  values = c(0, 2.9/5, 1),              # Define positions of the colors (normalized)
  breaks = seq(-2, 2, by = 1),        # Custom tick marks
  labels = seq(-2, 2, by = 1)         # Corresponding labels
) + guides(edge_colour = "none")

