---
title: "Fig. 6F"
author: "Zidao Wang"
date: "2026-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# AddModuleScore to calculate MET signature score for each cell
# Create the MET gene list
MET_genes_science2016 <- MET_science2016$Gene
mousify <- function(a){
  return(paste0(substr(a,1,1), tolower(substr(a,2,nchar(a)))))
}
MET_genes_science2016 <- sapply(MET_genes_science2016, mousify)
# Assuming you have a Seurat object all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5 <- AddModuleScore(
  object = all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5,           # The Seurat object
  features = list(MET_genes_science2016),  # List of genes representing the signature
  name = "GeneSignatureScore"    # Name of the new score (this will be added to metadata)
)
# Visualize the Gene Signature Score across clusters
# Reorder the cell types in the Seurat object (custom order)
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5@active.ident <- factor(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5@active.ident, 
                                          levels = c("Non_MD", "MD", "Trans_tdTomatoH", "Trans_tdTomatoL", "Mesenchymal cells-1", 
                                                     "Mesenchymal cells-2", "Mesenchymal cells-3", "Perivascular cells", "Myometrial cells", 
                                                     "Trophoblast cells", "Endothelial cells-1", "Endothelial cells-2", "Endothelial cells-3", 
                                                     "Plasma cells", "Immune cells-1", "Immune cells-2", "Immune cells-3", "Immune cells-4", 
                                                     "Immune cells-5"))
VlnPlot(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, features = "GeneSignatureScore1", 
        idents = c("MD", "Trans_tdTomatoH", "Mesenchymal cells-1", "Mesenchymal cells-2", "Mesenchymal cells-3", "Perivascular cells"), 
        pt.size = 0) + NoLegend()

