---
title: "Fig. 6D"
author: "Zidao Wang"
date: "2025-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Cnetplot
##Copy row names into a new column named 'gene_id'
Trans_tdTomatoH_markers_filtered$gene_id <- rownames(Trans_tdTomatoH_markers_filtered)
##Optional: Move the new column to the first position
Trans_tdTomatoH_markers_filtered <- Trans_tdTomatoH_markers_filtered[, c("gene_id", setdiff(names(Trans_tdTomatoH_markers_filtered), "gene_id"))]
###Create a data frame for Foldchange argument in cnetplot
fold_changes <- setNames(Trans_tdTomatoH_markers_filtered$avg_log2FC, Trans_tdTomatoH_markers_filtered$gene_id)
fold_changes <- sort(fold_changes, decreasing = T)
###Define a vector of specific GO terms
selected_terms <- c("extracellular matrix organization", "wound healing", "cell junction assembly", "Wnt signaling pathway", "regulation of epithelial cell proliferation")
####Plot cnetplot
cnetplot(
  GO_results,
  showCategory = selected_terms,
  color.params = list(foldChange = fold_changes, edge = T),
  layout = "kk",
  circular = F,
  ggplot2.params = list(
    max.overlaps = 500  # Increase the max number of overlaps allowed
  )
) + scale_color_gradientn(
  name = "Fold Change",
  colors = c("blue", "white", "red"),  # Define multiple colors
  values = c(0, 3.4/5, 1),              # Define positions of the colors (normalized)
  breaks = seq(-6, 6, by = 2),        # Custom tick marks
  labels = seq(-6, 6, by = 2)         # Corresponding labels
) + guides(edge_colour = "none")
