---
title: "Fig. 6A"
author: "Zidao Wang"
date: "2025-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Mes_Epi_MET_genes <- c("Col5a2", "Col1a1", "Col3a1", "Col6a4", "Antxr1", "Atp8b1", "Svep1", "Slit3", "Sox5", "tdTomato", "Pdgfra", "Pdgfrb", "Robo2", "Rorb", "Rxfp1", "Cdh11", "Vim", "Cd34", "Des", "Dio2", "Fbln1", "Fbln2", "Mfap4", "Mfap5", "Thy1", "Bcat1", "Fut9", "Prom1", "Kctd1", "Mecom", "Erbb4", "Epcam", "Cdh1", "Foxa2", "Wfdc2", "Pax2", "Pax8", "Krt8", "Krt14", "Krt18", "Serpina1e", "Car2", "Cd9", "Cd24a", "Cldn4", "Clu", "Dsp", "Fxyd3", "Fxyd4", "Lcn2", "Muc1", "Olfm1", "Plet1", "Sdc4", "Sprr2f", "Trpv6", "Pelo", "Cited1", "Fzd7", "Gdnf", "Six2", "Tcf15", "Wnt9b", "Wnt4", "Wt1", "Grem1", "Sall1", "Bmp4", "Bmp7", "Ehf", "Elf3", "Gata3", "Irf6", "Klf4", "Ovol1", "Ovol2")
DotPlot(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, features = Mes_Epi_MET_genes, 
        idents = c("Mesenchymal cells-1", "Mesenchymal cells-2", "Mesenchymal cells-3", "Trans_tdTomatoH", "Trans_tdTomatoL", "MD", "Non_MD", 
                   "Perivascular cells"), 
        col.min = 0, col.max = 2) + RotatedAxis() +
  scale_y_discrete(labels = c("Mesenchymal cells-1" = "Mes1", 
                              "Mesenchymal cells-2" = "Mes2", 
                              "Mesenchymal cells-3" = "Mes3", 
                              "MD" = "MD epi", 
                              "Non_MD" = "Non_MD epi", 
                              "Trans_tdTomatoH" = "MD trans", 
                              "Trans_tdTomatoL" = "Non_MD trans", 
                              "Perivascular cells" = "Peri"
                              ))
