---
title: "Fig. 6E"
author: "Zidao Wang"
date: "2026-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Trajectory analysis using Mes_Transreal_MD_Peri
Idents(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) <- "Trans_MD_cell"
sub <- subset(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, idents = c("Mesenchymal cells-1", "Mesenchymal cells-2", "Mesenchymal cells-3", 
                                                                                    "Perivascular cells", "Trans_tdTomatoH", "MD"))
sub <- SCTransform(object = sub)
sub <- RunPCA(object = sub)
cds <- SeuratWrappers::as.cell_data_set(sub, assay = "RNA")
cds <- estimate_size_factors(cds)
# Assuming gene names are stored in the row names of the expression matrix
gene_names <- rownames(GetAssayData(sub, assay = "RNA", layer = "counts"))
# Create a data frame with gene_short_name
gene_metadata <- data.frame(gene_short_name = gene_names, row.names = gene_names)
# Add gene_metadata to rowData
rowData(cds) <- gene_metadata
cds <- cluster_cells(cds)
cds <- learn_graph(cds, use_partition = T)
plot_cells(cds, show_trajectory_graph = T, color_cells_by = "partition")

get_earliest_principal_node <- function(cds, time_bin="E18.5"){
  cell_ids <- which(colData(cds)[, "groups"] == time_bin)
  
  closest_vertex <-
    cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
  closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
  root_pr_nodes <-
    igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
                                                              (which.max(table(closest_vertex[cell_ids,]))))]
  
  root_pr_nodes
}
cds <- order_cells(cds, root_pr_nodes = get_earliest_principal_node(cds))
umap_plot <- plot_cells(cds,
           color_cells_by = "pseudotime",
           label_cell_groups=F,
           label_leaves=T,
           label_branch_points=T,
           graph_label_size=1.5
           ) +
  theme_void() +  # Removes all background elements, including axis lines
  theme(
    legend.position = "none",  # Remove the legend
    plot.title = element_blank()  # Remove the title
)

