---
title: "Supp Fig. 2K"
author: "Zidao Wang"
date: "2025-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Epi <- AddModuleScore(Epi, features = list(pyroptosis_genes), name = "ProPyroptosisScore")
ggplot(metadata, aes(x = groups, y = ProPyroptosisScore1, fill = Trans_MD_cell)) +
  geom_boxplot(position = position_dodge(width = 0.75), outlier.shape = NA) +
  stat_summary(fun = mean, geom = "line",
               aes(group = Trans_MD_cell, color = Trans_MD_cell),
               position = position_dodge(width = 0.75), size = 1) +
  stat_summary(fun = mean, geom = "point",
               aes(group = Trans_MD_cell, color = Trans_MD_cell),
               position = position_dodge(width = 0.75), size = 3) +
  scale_color_manual(values = c("MD" = "#bf0a30", "Non_MD" = "#0041c2")) +
  labs(title = "Pyroptosis Module Score by Cell Type and Time",
       x = "Time Point",
       y = "Module Score (ProPyroptosisScore1)",
       fill = "Cell Type",
       color = "Cell Type") +
  theme_classic()
# Calculate p-values for each time point
stat_results <- metadata %>%
  group_by(groups) %>%
  dplyr::summarize(p_value = wilcox.test(ProPyroptosisScore1 ~ Trans_MD_cell)$p.value)
