---
title: "Supp Fig. 7C"
author: "Zidao Wang"
date: "2026-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Create the eMSC gene list
eMSC_genes <- c("Mcam", "Pdgfrb", "Itgb1", "Itga4", "Itgae", "Cd44", "Nt5e", "Thy1", "Eng", "Kit", "Susd2", "Pou5f1", "Cspg4", "Abcg2", "Cd34", "Klf4")
#Calculate eMSC module score
all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5 <- AddModuleScore(
  object = all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5,           # The Seurat object
  features = list(eMSC_genes),  # List of genes representing the signature
  name = "GeneSignatureScore"    # Name of the new score (this will be added to metadata)
)
# Visualize the Gene Signature Score across clusters
# Reorder the cell types in the Seurat object (custom order)
Idents(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5) <- "Trans_MD_cell"
VlnPlot(all_merged_harmony_cluster_v2_PrepSCT_12sample_old_res0.5, features = "GeneSignatureScore1", 
        idents = c("MD", "Non_MD", "Trans_tdTomatoH", "Trans_tdTomatoL", "Mesenchymal cells-1", "Mesenchymal cells-2", "Mesenchymal cells-3", "Perivascular cells", "Myometrial cells"), 
        pt.size = 0) + NoLegend()

